Don't call xf86DisableRandR in ABI_VIDEODRV_VERSION 24 & later
The API was removed by Xserver commit dd00e5466a0e4ea313d1860824da4123692827ed
in xorg-server-1.20.0 and later.

Found by gcc -Werror=implicit:

savage_driver.c: In function ‘SavagePreInit’:
savage_driver.c:1237:13: error: implicit declaration of function
 ‘xf86DisableRandR’; did you mean ‘xf86DisableIO’?
 [-Werror=implicit-function-declaration]
 1237 |             xf86DisableRandR();
      |             ^~~~~~~~~~~~~~~~
      |             xf86DisableIO

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>